routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

Route::get('/', 'ForumController@index');

Auth::routes();

Route::get('/home', 'ForumController@index')->name('home');

Route::middleware(['auth'])->group(function () {
  Route::resource('/category', 'CategoryController');
  Route::resource('/role', 'RoleController');
  Route::resource('/topic', 'ForumController');
  Route::resource('/profile', 'UserController');
  Route::resource('/comment', 'CommentController');


  //Read Topic
  // Route::get('/topic', 'ForumController@index');
  Route::get('/topic/{topic}/view', 'ForumController@view');

  //Update
  Route::get('/topic/{topic_id}/edit', 'ForumController@edit');
  Route::put('/topic/{topic_id}', 'ForumController@update');

  //Create Comment
  Route::post('/topic/{topic}/view', 'CommentController@store');
});




// //CRUD Category
// //Create
// Route::get('/category/create', 'CategoryController@create');
// Route::post('category', 'CategoryController@store');

// //Read
// Route::get('/category', 'CategoryController@index');

// //Update
// Route::get('/category/{category_id}/edit', 'CategoryController@edit');
// Route::put('category/{category_id}', 'CategoryController@update');

// //Delete
// Route::delete('category/{category_id}', 'CategoryController@destroy');

// //CRUD Role
// //Create
// Route::get('/role/create', 'RoleController@create');
// Route::post('role', 'RoleController@store');

// //Read
// Route::get('/role', 'RoleController@index');

// //Update
// Route::get('/role/{role_id}/edit', 'RoleController@edit');
// Route::put('role/{role_id}', 'RoleController@update');

// //Delete
// Route::delete('role/{role_id}', 'RoleController@destroy');

app/Category.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    protected $table = "categories";
    protected $fillable = ["name"];

    public function topic()
    {
      return $this->hasMany(Topic::class);
    }
}

app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Category;
use App\Topic;

class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $category = Category::withCount('topic')->get();
        // return $category;
        return view('category.index', compact('category'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('category.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'name' => 'required',
        ],
        [    
            'name.required' => 'Category Name is required',
        ]);

        $category = new Category;
        $category->name = $request->name;
        $category->save();

        return redirect('/category');
    }

        

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
      $topics = Topic::with('comment')
        ->where('category_id', '=', $id)
        ->get();
      $category = Category::find($id);
      return view('category.show', compact('topics', 'category'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $category = Category::find($id);
        
        return view('category.edit', compact('category'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'name' => 'required',
        ],
        [    
            'name.required' => 'Category Name is required',
        ]);

        $category = Category::find($id);
        $category->name = $request['name'];
        $category->save();

        return redirect('/category');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $category = Category::find($id);
        $category->delete();
        return redirect('/category');
    }
}

resources/views/category/create.blade.php
@extends('layouts.main')
@section('title')
Add Category
@endsection

@section('content')
<form method="POST" action="/category">
    @csrf
    <div class="form-group">
      <label>Category Name</label>
      <input type="text" name="name" class="form-control">
    </div>
    @error('name')
    <div class="alert alert-danger">{{ $message }}</div>
    @enderror
    
    <button type="submit" class="btn btn-primary">Submit</button>
  </form>
@endsection

resources/views/category/edit.blade.php
@extends('layouts.main')
@section('title')
Edit Category
@endsection

@section('content')
<form method="POST" action="/category/{{$category->id}}">
    @csrf
    @method('put')
    <div class="form-group">
      <label>Category Name</label>
      <input type="text" name="name" value="{{$category->name}}" class="form-control">
    </div>
    @error('name')
    <div class="alert alert-danger">{{ $message }}</div>
    @enderror
    
    <button type="submit" class="btn btn-primary">Submit</button>
  </form>
@endsection

resources/views/category/index.blade.php
@extends('layouts.main')
@section('title')
Category
@endsection

@section('card-tools')
  @if (auth()->user()->role_id == 2)
    <a href="{{route('category.create')}}" class="btn btn-primary mb-3">Add Category</a>       
  @endif
@endsection

@section('content')
<ul class="list-group">
  @forelse ($category as $key => $item)
    <li class="list-group-item">
      <a href="{{route('category.show', $item->id)}}">
        <h2>{{$item->name}}</h2>
      </a>
      <p>{{$item->topic_count}} threads</p>
    </li>
  @empty
      <h1>Data Not Found</h1>
  @endforelse
</ul>
@endsection

resources/views/category/show.blade.php
@extends('layouts.main')
@section('title')
{{$category->name}}
@endsection

@section('content')
<ul class="list-group">
  @forelse ($topics as $key => $item)
    <li class="list-group-item">
      <a href="{{route('topic.show', $item->id)}}">
        <h2>{{$item->title}}</h2>
      </a>
      by <a href="{{route('profile.show', $item->user->id)}}">{{$item->user->name}}</a> |
      <span>category: <a href="{{route('category.show', $item->category->id)}}">{{$item->category->name}}</a></span> |
      <span class="timestamp">{{$item->created_at->diffForHumans()}}</span>
    </li>
  @empty
      <h1>Data Not Found</h1>
  @endforelse
</ul>
@endsection