routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

Route::get('/', 'ForumController@index');

Auth::routes();

Route::get('/home', 'ForumController@index')->name('home');

Route::middleware(['auth'])->group(function () {
  Route::resource('/category', 'CategoryController');
  Route::resource('/role', 'RoleController');
  Route::resource('/topic', 'ForumController');
  Route::resource('/profile', 'UserController');
  Route::resource('/comment', 'CommentController');


  //Read Topic
  // Route::get('/topic', 'ForumController@index');
  Route::get('/topic/{topic}/view', 'ForumController@view');

  //Update
  Route::get('/topic/{topic_id}/edit', 'ForumController@edit');
  Route::put('/topic/{topic_id}', 'ForumController@update');

  //Create Comment
  Route::post('/topic/{topic}/view', 'CommentController@store');
});




// //CRUD Category
// //Create
// Route::get('/category/create', 'CategoryController@create');
// Route::post('category', 'CategoryController@store');

// //Read
// Route::get('/category', 'CategoryController@index');

// //Update
// Route::get('/category/{category_id}/edit', 'CategoryController@edit');
// Route::put('category/{category_id}', 'CategoryController@update');

// //Delete
// Route::delete('category/{category_id}', 'CategoryController@destroy');

// //CRUD Role
// //Create
// Route::get('/role/create', 'RoleController@create');
// Route::post('role', 'RoleController@store');

// //Read
// Route::get('/role', 'RoleController@index');

// //Update
// Route::get('/role/{role_id}/edit', 'RoleController@edit');
// Route::put('role/{role_id}', 'RoleController@update');

// //Delete
// Route::delete('role/{role_id}', 'RoleController@destroy');

app/Topic.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Topic extends Model
{
    protected $table = "topics";
    protected $fillable = ["title", "content", "image", "category_id", "user_id"];

    public function user(){
        return $this->belongsTo(User::class);
    }

    public function category(){
      return $this->belongsTo(Category::class);
    }

    public function comment(){
        return $this->hasMany(Comment::class);
    }

    // public function category(){
    //     return $this->hasMany(Category::class);
    // }

}

resources/views/topic/create.blade.php
@extends('layouts.main')
@section('title')
Add Topic
@endsection

@push('script')
<script src="https://cdn.tiny.cloud/1/w87cwhy6axadle00918qysz0z2pvnwkmp6hdplhqmdggqks9/tinymce/5/tinymce.min.js" referrerpolicy="origin"></script>
<script>
  tinymce.init({
    selector: 'textarea'
  });
</script>
<script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
<script>
  // In your Javascript (external .js resource or <script> tag)
  $(document).ready(function() {
  $('.js-example-basic-single').select2();
});
</script>
@endpush

@push('style')
  <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
@endpush

@section('content')
<form method="POST" action="/topic" enctype="multipart/form-data">
    @csrf
    <div class="form-group">
      <label>Category</label><br>
      <select name="category_id" class="form-control js-example-basic-single" style="width: 100%" id="">
        <option value="">-- Category --</option>
        @foreach ($category as $item)
            <option value="{{$item->id}}">{{$item->name}}</option>
        @endforeach
      </select>
    </div>
    <div class="form-group">
      <label>Title</label>
      <input type="text" name="title" class="form-control">
    </div>
    @error('title')
    <div class="alert alert-danger">{{ $message }}</div>
    @enderror
    <div>
      <label>Content</label>
      <textarea name="content" class="form-control"></textarea>
    </div>
    <div class="form-group">
      <label>Image</label>
      <input type="file" name="image" class="form-control">
    </div>

    <button type="submit" class="btn btn-primary">Submit</button>
  </form>
@endsection

resources/views/topic/edit.blade.php
@extends('layouts.main')
@section('title')
Edit Topic
@endsection

@push('script')
<script src="https://cdn.tiny.cloud/1/w87cwhy6axadle00918qysz0z2pvnwkmp6hdplhqmdggqks9/tinymce/5/tinymce.min.js" referrerpolicy="origin"></script>
<script>
  tinymce.init({
    selector: 'textarea'
  });
</script>
<script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
<script>
  // In your Javascript (external .js resource or <script> tag)
  $(document).ready(function() {
  $('.js-example-basic-single').select2();
});
</script>
@endpush

@push('style')
  <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
@endpush

@section('content')
<form method="POST" action="{{route('topic.update', $topic->id)}}" enctype="multipart/form-data">
  @method('PUT')
  @csrf
    <div class="form-group">
      <label>Category</label><br>
      <select id="category" name="category_id" class="form-control js-example-basic-single" style="width: 100%">
        @foreach ($categories as $item)
          @if ($topic->category_id == $item->id)
            <option value="{{$item->id}}" selected>{{$item->name}}</option>        
          @else
            <option value="{{$item->id}}">{{$item->name}}</option>    
          @endif
        @endforeach
      </select>
    </div>
    <div class="form-group">
      <label>Title</label>
      <input type="text" name="title" value="{{$topic->title}}" class="form-control">
    </div>
    @error('title')
    <div class="alert alert-danger">{{ $message }}</div>
    @enderror
    <div>
      <label>Content</label>
      <textarea name="content" value="" class="form-control">{{$topic->content}}</textarea>
    </div>
    <div class="form-group">
      <label>Image</label>
      <input type="file" name="image" value="{{$topic->image}}" class="form-control">
    </div>

    <button type="submit" class="btn btn-primary">Submit</button>
  </form>
@endsection

resources/views/topic/index.blade.php
@extends('layouts.main')
@section('title')
Topic
@endsection

@section('card-tools')
  <a href="{{route('topic.create')}}" class="btn btn-primary mb-3">Add</a>
@endsection

@section('content')

  <ul class="list-group">
    @forelse ($topic as $item)
      <li class="list-group-item">
        <a href="{{route('topic.show', $item->id)}}">
          <h2>{{$item->title}}</h2>
        </a>
        by <a href="{{route('profile.show', $item->user->id)}}">{{$item->user->name}}</a> |
        <span>category: <a href="{{route('category.show', $item->category->id)}}">{{$item->category->name}}</a></span> |
        <span class="timestamp">{{$item->created_at->diffForHumans()}}</span>
      </li>
    @empty
      <h1>Data Not Found</h1>
    @endforelse
  </ul>
  @endsection

resources/views/topic/show.blade.php
@extends('layouts.main')
@section('title')
{{$topic->title}}
@endsection

@section('card-tools')
      @if (auth()->user()->id == $topic->user_id)
        <form class="mt-2" action="/topic/{{$topic->id}}" method="POST">
          <a href="/topic/{{$topic->id}}/edit" class="btn btn-warning btn-sm">Edit</a>
          @csrf
          @method('delete')
          <input type="submit" value="Delete" class="btn btn-danger btn-sm">
        </form>
      @endif
@endsection

@section('content')
<div class="panel panel-headline">
    <div class="panel-heading">
        <p class="text-muted">
          {{$topic->created_at->diffForHumans()}} by 
          <a href="{{route('profile.show', $topic->user->id)}}">{{$topic->user->name}}</a> under category 
          <a href="{{route('category.show', $topic->category->id)}}">{{$topic->category->name}}</a>
        </p>
    </div>
    <div class="panel-body">
        <div class="d-flex justify-content-center">
          <img src="{{asset('gambar/'.$topic->image)}}" alt="featured image">
        </div>
        
        <p class="lead" >{!!$topic->content!!}</p>
        <hr>
        <div class="btn-group">
            <button id="btn-main-comment" class="btn btn-outline-secondary btn-sm"><i class="lnr lnr-bubble"></i>Add Comment</button>
        </div> 
        <form action="{{route('comment.store')}}" method="POST" id="main-comment" style="margin-top:10px;display:none">
            @csrf
            <input type="hidden" name="topic_id" value="{{$topic->id}}">
            <input type="hidden" name="parent" value="0">
            <textarea class="form-control" name="comment"></textarea>
            <input type="submit" class="btn btn-primary mt-2" value="Send">
        </form><br><br>
        <h4>Comments</h4>
            <ul class="list-unstyled activity-list">
                @foreach ($topic->comment()->where('parent', 0)->orderBy('created_at', 'desc')->get() as $comment)
                <li class="border rounded p-3 my-1">
                    <p><b>{{$comment->user->name}}</b><br>
                    {{$comment->comment}}<br><span class="timestamp">{{$comment->created_at->diffForHumans()}}
                    </span>
                    @if (auth()->user()->id == $comment->user_id)
                      <form class="d-inline" action="{{route('comment.destroy', $comment->id)}}" method="POST">
                        @csrf
                        @method('delete')
                        <a href="{{route('comment.edit', $comment->id)}}">Edit</a> | 
                        <input type="submit" value="Delete" class="btn btn-link p-0 d-inline">
                      </form>
                    @endif
                    </p>
                    <form action="{{route('comment.store')}}" method="POST">
                        @csrf
                        <input type="hidden" name="topic_id" value="{{$topic->id}}">
                        <input type="hidden" name="parent" value="{{$comment->id}}">
                        <input type="text" name="comment" class="form-control">
                        <input type="submit" class="btn btn-primary btn-xs mt-2" value="Send">
                    </form>
                    <br>
                        @foreach($comment->childs()->orderBy('created_at', 'desc')->get() as $child)
                            <p style="padding-left: 2em"><b>{{$child->user->name}}</b><br>
                            {{$child->comment}}<br><span class="timestamp">{{$child->created_at->diffForHumans()}}
                            </span>
                            @if (auth()->user()->id == $child->user->id)
                            <span class="mt-2" action="" method="POST">
                            <span>| <a href="{{route('comment.edit', $child->id)}}">Edit</a> | <a href="/topic/{{$topic->id}}/{{$child->id}}/delete">Delete</a></span>
                            @endif
                            </p>
                        @endforeach
                </li>    
                @endforeach
          </ul>
    </div>
</div>

@endsection

@push('script')
    <script>
        $(document).ready(function(){
            $('#btn-main-comment').click(function(){
                $('#main-comment').toggle('slide');
            });
        });
    </script>
@endpush

resources/views/topic/view.blade.php
@extends('layouts.main')
@section('title')
Topic
@endsection

@section('content')
<div class="panel panel-headline">
    <div class="panel-heading">
        <h3 class="panel-title">{{$topic->title}}</h3>
        <p class="panel-subtitle">by {{$topic->user->name}}. {{$topic->created_at->diffForHumans()}}</p>
    </div>
    <div class="panel-body">
        {{$topic->content}}
        @if (auth()->user()->id == $topic->user_id)
        <form class="mt-2" action="/topic/{{$topic->id}}" method="POST">
          <a href="/topic/{{$topic->id}}/edit" class="btn btn-warning btn-sm">Edit</a>
          @csrf
          @method('delete')
          <input type="submit" value="Delete" class="btn btn-danger btn-sm">
        </form>
        @endif
        <hr>
        <div class="btn-group">
            <button id="btn-main-comment" class="btn btn-default"><i class="lnr lnr-bubble"></i>Comment</button>
        </div> 
        <form action="" method="POST" id="main-comment" style="margin-top:10px;display:none">
            @csrf
            <input type="hidden" name="topic_id" value="{{$topic->id}}">
            <input type="hidden" name="parent" value="0">
            <textarea class="form-control" name="comment"></textarea>
            <input type="submit" class="btn btn-primary" value="Send">
        </form><br><br>
        <h4>Comments</h4>
            <ul class="list-unstyled activity-list">
                @foreach ($topic->comment()->where('parent', 0)->orderBy('created_at', 'desc')->get() as $comment)
                <li>
                    <p><a href="#">{{$comment->user->name}}</a><br>
                    {{$comment->comment}}<br><span class="timestamp">{{$comment->created_at->diffForHumans()}}
                    </span></p>
                    <form action="" method="POST">
                        @csrf
                        <input type="hidden" name="topic_id" value="{{$topic->id}}">
                        <input type="hidden" name="parent" value="{{$comment->id}}">
                        <input type="text" name="comment" class="form-control">
                        <input type="submit" class="btn btn-primary btn-xs" value="Send">
                    </form>
                    <br>
                        @foreach($comment->childs()->orderBy('created_at', 'desc')->get() as $child)
                            <p style="padding-left: 2em"><a href="#">{{$child->user->name}}</a><br>
                            {{$child->comment}}<br><span class="timestamp">{{$child->created_at->diffForHumans()}}
                            </span></p>
                        @endforeach
                </li>    
                @endforeach
          </ul>
    </div>
</div>

@endsection

@push('script')
    <script>
        $(document).ready(function(){
            $('#btn-main-comment').click(function(){
                $('#main-comment').toggle('slide');
            });
        });
    </script>
@endpush